"""
Identifier:     galfitx/mask.py
Name:           mask.py
Description:    generate mask image for fitting
Author:         Chao Ma
Created:        2026-01-19
Modified-History:
    2026-01-19, Chao Ma, created
"""

import os
import numpy as np
import string
from astropy.io import fits, ascii
from galfitx.read_sersic_results import read_sersic_results
from typing import List, Optional, Tuple, Any, Union


def create_mask(
    weight_name: str,
    seg_name: str,
    catalog_name: str,
    paramfile: str,
    mask_file: str,
    mask_file_primary: str,
    current: int,
    scale: float,
    offset: float,
    limgal: float,
    b: int,
) -> Tuple[List[int], List[int]]:
    """
    Create a binary mask for a postage stamp around a primary source.

    The mask is constructed on a cutout defined by a stamp parameter file.
    Pixels are classified as:
    - 0 (good) : belonging to the primary source or to secondary sources that overlap with the primary and are bright enough.
    - 1 (masked) : bad pixels (from weight image), pixels of other segmentation regions (tertiary sources), and pixels outside any source ellipse.
    The final mask is written to a FITS file (`mask_file + ".fits"`). If
    `b == 1`, an additional mask containing only the primary source is saved
    as `mask_file_primary + ".fits"`.

    Parameters
    ----------
    weight_name : str
        Path to the weight (or science) FITS image. Used to obtain the header
        and to identify zero‑weight pixels (which are masked).
    seg_name : str
        Path to the segmentation FITS image (from SExtractor).
    catalog_name : str
        Path to the SExtractor catalog (ASCII). Must contain columns:
        'label', 'xcentroid', 'ycentroid', 'ellipticity', 'orientation',
        'semimajor_sigma', 'kron_radius', 'mag_auto'.
    paramfile : str
        Stamp file generated by `create_stamp_file`. Expected columns:
        pnum, px, py, pxlo, pxhi, pylo, pyhi.
    mask_file : str
        Base name for the output mask FITS file (the extension ".fits" is added).
    mask_file_primary : str
        Base name for the primary‑only mask FITS file (only written if `b == 1`).
    current : int
        Index (0‑based) of the current (primary) source in the catalog.
    scale : float
        Factor multiplying the Kron radius to define the source extent.
    offset : float
        Additional offset (in pixels) added to the scaled radius.
    limgal : float
        Magnitude threshold for secondary classification. A source with
        `mag_auto` < `primary_mag + limgal` and overlapping the primary is
        considered a secondary; otherwise it is treated as tertiary.
    b : int
        Band index. If `b == 1`, the primary‑only mask is written.

    Returns
    -------
    corner : list of int
        Two‑element list `[pxlo, pylo]` giving the lower‑left corner of the
        postage stamp in the original image pixel coordinates (0‑based).
    objects : list of int
        Indices (in the catalog) of sources that are either the primary or
        secondaries (i.e., sources that will be included in the GALFIT model).
    """

    wht = fits.open(weight_name)[0].data
    header = fits.open(weight_name)[0].header
    ny_big, nx_big = wht.shape

    seg = fits.open(seg_name)[0].data

    cat = ascii.read(catalog_name)
    rad = scale * cat["semimajor_sigma"] * cat["kron_radius"] + offset

    paramdata = ascii.read(paramfile, names=["pnum", "px", "py", "pra", "pdec", "pxlo", "pxhi", "pylo", "pyhi", "pixscl"])

    idx = np.where(paramdata["pnum"] == cat[current]["label"])
    if idx[0].size == 0:
        raise ValueError(f"no postage stamp definition found for current object{cat[current]['label']}")

    pnum = paramdata["pnum"][idx]
    px = paramdata["px"][idx]
    py = paramdata["py"][idx]
    pxlo = int(max(min(paramdata["pxlo"][idx], nx_big - 1), 0))
    pxhi = int(max(min(paramdata["pxhi"][idx], nx_big - 1), 0))
    pylo = int(max(min(paramdata["pylo"][idx], ny_big - 1), 0))
    pyhi = int(max(min(paramdata["pyhi"][idx], ny_big - 1), 0))

    mask = wht[pylo: pyhi + 1, pxlo: pxhi + 1]
    segm = seg[pylo: pyhi + 1, pxlo: pxhi + 1]
    badpix = np.where(mask == 0)
    mask *= 0
    ny, nx = mask.shape

    # objects for the GALFIT start file (primary source must be included)
    objects = [current]

    ntab = len(cat["label"])

    # need modfiy this for images with different coordinate systems
    theta = cat["orientation"] * np.pi / 180  # convert degrees to radian

    # calculate the radius array for the primary source
    arr_current = dist_ellipse(
        [pxhi - pxlo + 1, pyhi - pylo + 1],
        cat[current]["xcentroid"] - pxlo,
        cat[current]["ycentroid"] - pylo,
        1.0 / (1.0 - cat[current]["ellipticity"]),
        theta[current] * 180 / np.pi - 90,
    )

    # loop over all sources in the catalog.
    for i in range(ntab):
        if i == current:
            continue
        # calculate the angle between the loop sources and the [current] object
        dx = cat[current]["xcentroid"] - cat[i]["xcentroid"]
        dy = cat[current]["ycentroid"] - cat[i]["ycentroid"]
        if dx == 0:
            angle = np.pi / 2.0
        else:
            angle = np.arctan(dy / dx)
        # calculate the angle pointing from the loop source to the [current] object
        # i.e,from the perspective of the _i_th source, how much you must rotate its own axis to point toward the current object.
        angle1 = angle - theta[i]
        # calculate the angle pointing from the [current] object to the loop source
        # from the perspective of the current object, how much you must rotate its image‐frame axis to point back at the loop source.
        angle2 = angle - theta[current]

        # calculate the extent of the loop source towards the [current] object
        r1 = np.sqrt(
            1.0
            / (np.sin(angle1) ** 2 / (rad[i] * (1 - cat[i]["ellipticity"])) ** 2 + np.cos(angle1) ** 2 / rad[i] ** 2)
        )
        # calculate the extent of the [current] source towards the loop object
        r2 = np.sqrt(
            1.0
            / (
                np.sin(angle2) ** 2 / (rad[current] * (1 - cat[current]["ellipticity"])) ** 2
                + np.cos(angle2) ** 2 / rad[current] ** 2
            )
        )
        # calculate the distance between the two objects
        d = np.sqrt(dx**2 + dy**2)

        xfac = rad[i] * (abs(np.sin(theta[i])) + (1 - cat[i]["ellipticity"]) * abs(np.cos(theta[i])))
        yfac = rad[i] * (abs(np.cos(theta[i])) + (1 - cat[i]["ellipticity"]) * abs(np.sin(theta[i])))

        xfac = max(xfac, 10)
        yfac = max(yfac, 10)

        major = max([xfac, yfac])
        minor = min([xfac, yfac])

        ang = theta[i] * 180 / np.pi  # convert radian to degrees
        ang %= 360  # contraint to [0,360)
        if ang > 180:
            ang -= 180
        if ang > 90:
            ang -= 180
        if abs(ang) < 45:
            xfac = major
            yfac = minor
        else:
            xfac = minor
            yfac = major
        xlo = min(max(round(cat[i]["xcentroid"] - xfac), 0), nx_big - 1)
        xhi = min(max(round(cat[i]["xcentroid"] + xfac), 0), nx_big - 1)
        ylo = min(max(round(cat[i]["ycentroid"] - yfac), 0), ny_big - 1)
        yhi = min(max(round(cat[i]["ycentroid"] + yfac), 0), ny_big - 1)
        # xlo,ylo,xhi,yhi are on the system of the input image, but not
        # on the postage stamp.
        xlo = min(max(xlo - pxlo, 0), nx - 1)
        xhi = min(max(xhi - pxlo, 0), nx - 1)
        ylo = min(max(ylo - pylo, 0), ny - 1)
        yhi = min(max(yhi - pylo, 0), ny - 1)
        # now it is shifted into the postage‐stamp’s pixel grid

        if np.sum([xhi - xlo + 1, yhi - ylo + 1]) > 2:
            arr = dist_ellipse(
                [xhi - xlo + 1, yhi - ylo + 1],
                cat[i]["xcentroid"] - pxlo - xlo,
                cat[i]["ycentroid"] - pylo - ylo,
                1.0 / (1.0 - cat[i]["ellipticity"]),
                theta[i] * 180 / np.pi - 90,
            )
        else:
            arr = 1e30

        small_mask = mask[ylo: yhi + 1, xlo: xhi + 1]

        faintlim = limgal  # has omit the star

        if (r1 + r2 > d) and (cat[i]["mag_auto"] < (cat[current]["mag_auto"] + faintlim)):
            # loop source has overlap with current --> secondary
            idx = np.where((arr <= rad[i]) & ((small_mask % 2) == 0))
            if idx[0].size > 0:
                small_mask[idx] += 1
            objects.append(i)
        else:
            # loop source has NO overlap with current --> tertiary
            plus = 2
            idx = np.where((arr <= rad[i]) & (small_mask < 2))
            if idx[0].size > 0:
                small_mask[idx] += plus

        if (r1 + r2 > d) and (cat[i]["mag_auto"] >= (cat[current]["mag_auto"] + faintlim)):
            # loop source has overlap with current --> secondary
            idx = np.where(
                (arr <= rad[i]) & ((small_mask % 2) == 0) & (arr_current[ylo: yhi + 1, xlo: xhi + 1] <= rad[current])
            )
            if idx[0].size > 0:
                small_mask[idx] = 0

        mask[ylo: yhi + 1, xlo: xhi + 1] = small_mask

    # set secondaries to 0
    idx = np.where((mask == 1) | (mask == 3))
    if idx[0].size > 0:
        mask[idx] = 0

    # clear area of primary
    arr = dist_ellipse(
        [nx, ny],
        cat[current]["xcentroid"] - pxlo,
        cat[current]["ycentroid"] - pylo,
        1.0 / (1.0 - cat[current]["ellipticity"]),
        theta[current] * 180 / np.pi - 90,
    )
    idx = np.where(arr <= rad[current])
    if idx[0].size > 0:
        mask[idx] = 0

    # update the header
    stamp_header = header.copy()  # avoid mutating the original
    stamp_header["CRPIX1"] -= pxlo  # Shift reference pixel
    stamp_header["CRPIX2"] -= pylo

    # create primary mask if band = 1
    if b == 1:
        arr = arr * 0
        arr[idx] = 1
        fits.writeto(mask_file_primary + ".fits", arr, header=stamp_header, overwrite=True)

    # set rest to 1
    mask = np.minimum(mask, 1)

    # pixels without weight in the wht image will be masked
    if badpix[0].size > 0:
        mask[badpix] = 1

    # any pixel in the segmentation map not from the primary or secondary
    # will be masked
    # again set all id number to 1
    mask1 = np.minimum(segm, 1)
    for i in range(len(objects)):
        idx = np.where((segm == cat[objects[i]]["label"]) & (segm > 0))
        if idx[0].size > 0:
            mask1[idx] = 0

    mask = np.minimum(mask + mask1, 1)
    fits.writeto(mask_file + ".fits", mask, header=stamp_header, overwrite=True)

    corner = [pxlo, pylo]

    return corner, objects


def dist_ellipse(
    n: Union[int, Tuple[int, int], List[int]], xc: float, yc: float, ratio: float, angle: float, double: bool = False
) -> np.ndarray:
    """
    Compute the elliptical distance from a center for each pixel in a grid.

    For a given grid size, this function calculates for each pixel the Euclidean
    distance in a coordinate system that is rotated and stretched according to
    the ellipse parameters. The resulting value can be interpreted as the
    "elliptical radius" (i.e., the distance from the center in the transformed
    space where the ellipse becomes a circle). Pixels lying on the ellipse
    defined by the parameters will have a value equal to the semi‑major axis
    length? Not exactly – the returned array gives the distance in the stretched
    coordinates, so it can be compared to a threshold to define elliptical masks.

    Parameters
    ----------
    n : int or tuple/list of two ints
        Dimensions of the output array. If an integer, a square array of size
        `n x n` is created. If a tuple/list of two integers `(nx, ny)`, the
        output shape will be `(ny, nx)` (rows = ny, columns = nx).
    xc : float
        X‑coordinate of the ellipse center (in pixel units, 0‑based from the
        left edge of the array).
    yc : float
        Y‑coordinate of the ellipse center (in pixel units, 0‑based from the
        top? – note that the function treats y increasing downward, consistent
        with image arrays).
    ratio : float
        Stretch factor along the rotated x‑axis. Typically this is the ratio of
        the semi‑major to semi‑minor axis (or vice‑versa) depending on convention.
        The code computes `sqrt((xtemp * ratio)**2 + ytemp**2)`, so larger
        `ratio` makes the ellipse more elongated in the direction of the rotated
        x‑axis.
    angle : float
        Rotation angle of the ellipse in degrees. The rotation is applied
        counter‑clockwise from the positive x‑axis (standard mathematical sense).
    double : bool, optional
        If True, use double‑precision (`float64`) for coordinates and the output
        array. If False (default), use single‑precision (`float32`). The choice
        affects memory usage and speed; single precision is usually sufficient
        for masking.

    Returns
    -------
    arr : 2D `~numpy.ndarray`
        Array of shape `(ny, nx)` containing the elliptical distance for each
        pixel. Values are floating point numbers.

    Raises
    ------
    ValueError
        If `n` is not an integer or a tuple/list of length 2.

    Examples
    --------
    >>> # Create a 100x100 array of distances from center (50,50) with axis ratio 2,
    >>> # rotated by 30 degrees, using single precision.
    >>> dist = dist_ellipse((100,100), 50, 50, 2.0, 30.0)
    >>> mask = dist <= 50   # mask of pixels inside an ellipse of "radius" 50
    """

    cosang = np.cos(angle * np.pi / 180)
    sinang = np.sin(angle * np.pi / 180)

    if isinstance(n, (tuple, list)) and len(n) == 2:
        nx = n[0]
        ny = n[1]
    elif isinstance(n, int):
        ny = nx = n
    else:
        raise ValueError("n must be an integer or a length-2 tuple/list")

    if double:
        # double-precision coords
        x = np.arange(nx, dtype=np.float64) - xc
        y = np.arange(ny, dtype=np.float64) - yc
        arr = np.empty((ny, nx), dtype=np.float64)
    else:
        # single-precision coords
        x = np.arange(nx, dtype=np.float32) - xc
        y = np.arange(ny, dtype=np.float32) - yc
        arr = np.empty((ny, nx), dtype=np.float32)

    # Rotate pixels to match ellipse orientation
    xcosang = x * cosang
    xsinang = x * sinang

    for i in range(ny):
        xtemp = xcosang + y[i] * sinang
        ytemp = -xsinang + y[i] * cosang
        arr[i, :] = np.sqrt((xtemp * ratio) ** 2 + ytemp**2)

    return arr


def prepare_galfitm(
    image_stamp_list: List[str],
    catalog_name: str,
    obj_file: str,
    corner: List[int],
    constr_file: str,
    mask_file: List[str],
    mask_primary_file: str,
    out_file: str,
    stamp_file: str,
    sigma_file: List[str],
    psf_file: List[str],
    sky_file: List[str],
    conv_box: float,
    zero_list: List[float],
    wave_list: List[str],
    label_list: List[str],
    nband: int,
    conmaxre: float,
    plate_scl: float,
    current: int,
    objects: Optional[List[int]] = None,
    setup: Any = None,
    use_cstsky: bool = False,
    cstsky_list: Optional[List[float]] = None,
) -> None:
    """
    Generate a GALFITM input file for multi‑band fitting of a primary source and its neighbours.

    This function writes a GALFITM configuration file (`obj_file`) that describes the
    multi‑band image data, PSF, masks, initial parameter guesses, constraints, and
    fitting options. It also writes a separate constraint file (`constr_file`).
    The function uses a SExtractor catalogue to obtain initial
    guesses and checks for existing GALFIT output files to reuse previous fits.

    Parameters
    ----------
    image_stamp_list : list of str
        Base names (without extension) of the multi‑band cutout FITS images.
        The actual filenames are constructed as `image_stamp_list[b] + ".fits"`.
    catalog_name : str
        Path to the SExtractor catalogue (ASCII) containing source parameters.
        Must include columns: label, xcentroid, ycentroid, flux_radius, orientation,
        ellipticity, mag_auto.
    obj_file : str
        Path where the GALFITM main configuration file will be written.
    corner : list of int
        Two‑element list `[pxlo, pylo]` giving the lower‑left corner of the
        postage stamp in the original image pixel coordinates (0‑based).
    constr_file : str
        Path where the constraint file for secondary sources will be written.
    mask_file : list of str
        Base names (without extension) of the mask FITS files for each band.
        The actual filenames are `mask_file[b] + ".fits"`.
    mask_primary_file : str
        Base name (without extension) of the primary‑only mask FITS file.
        The actual filename is `mask_primary_file + ".fits"`.
    out_file : str
        Base name for the GALFITM output FITS file (without path or extension).
        The full output path is built using `setup.outdir`.
    stamp_file : str
        Path to the stamp file generated by `create_stamp_file`. Expected columns:
        id, x, y, xlo, xhi, ylo, yhi.
    sigma_file : list of str
        Base names (without extension) of the sigma (noise) FITS files for each band.
        Use "none" to indicate no sigma image.
    psf_file : list of str
        Base names (without extension) of the PSF FITS files for each band.
    sky_file : list of str
        Paths to text files containing sky background estimates for each band.
        Each file should contain five numbers: sky, dsky, skyrad, sky_magobj, flag.
    conv_box : float
        Size of the convolution box (same in x and y). Will be cast to integer.
    zero_list : list of float
        Magnitude zeropoints for each band.
    wave_list : list of str
        Wavelengths (as strings) for each band, used in GALFITM ≥4.0.
    label_list : list of str
        Band labels (e.g., 'F090W') used in filenames and output.
    nband : int
        Number of bands (must equal the length of the above lists).
    conmaxre : float
        Maximum allowed half‑light radius (Re) in pixels.
    plate_scl : float
        Plate scale in arcsec/pixel (same in x and y).
    current : int
        Index (0‑based) of the current (primary) source in the catalogue.
    objects : list of int, optional
        Indices (0‑based) of all sources (primary + secondaries) to be fitted.
        If None, no sources are written (the function would produce an incomplete file).
    setup : Any
        A configuration object with attributes:
            - outdir : output directory for GALFITM files
            - version : GALFITM version (≥4.0 enables multi‑band syntax)
            - do_restrict : whether to restrict polynomial degree based on bad pixels
            - restrict_frac_primary : fraction of bad pixels threshold (as percent)
            - conminn, conmaxn : Sérsic index constraints
            - conminm, conmaxm : magnitude constraints
            - cheb : list of Chebyshev orders for each parameter (x, y, mag, re, n, q, pa)
            - gal_output : GALFIT output format
            - stamp_pre : (unused?) kept for compatibility
            - wavelength : (unused?) kept for compatibility
    use_cstsky : bool, optional
        If True, use constant sky values from `cstsky_list` instead of reading `sky_file`.
    cstsky_list : list of float, optional
        Constant sky background values for each band (used if `use_cstsky=True`).

    Returns
    -------
    None
        The function writes two files (`obj_file` and `constr_file`) and does not return
        any value.

    Notes
    -----
    - For sources, a constraint file is written first.
    - If a GALFIT output file for a source already exists (named
      `./galfit/output<label>.fits`), its best-fitting parameters are reused.
    - The function modifies magnitudes for sources with `mag_auto > 80` to avoid
      unrealistic values.
    - Parameter bounds are enforced using the provided constraints.
    - The polynomial degree for each parameter is set to `min(cheb_order+1, maxdeg)`
      where `maxdeg` may be reduced if too many bad pixels are found in the primary mask.
    """

    table = ascii.read(catalog_name)
    header = fits.open(image_stamp_list[0] + ".fits")[0].header
    xmax = header["NAXIS1"]
    ymax = header["NAXIS2"]

    # write constraint file for secondaries
    with open(constr_file, "w") as f:
        # header lines
        f.write("# Component/    parameter   constraint  Comment\n")
        f.write("# operation                  values\n")

        # loop from 2 to len(objects)+1; 2: primary; 3...: secondary
        for i in range(2, len(objects) + 2):
            # Write each constraint line
            f.write(f"{i:>12} n {setup.conminn} to {setup.conmaxn}\n")
            f.write(f"{i:>12} re 0.3 to {setup.conmaxre}\n")
            f.write(f"{i:>12} q 0.01 to 1.\n")
            f.write(f"{i:>12} mag {setup.conminm} {setup.conmaxm}\n")
            f.write(f"{i:>12} mag 0 to 40\n")
            f.write(f"{i:>12} x {-xmax/10.0} {xmax/10.0}\n")
            f.write(f"{i:>12} y {-ymax/10.0} {ymax/10.0}\n")

    # write obj file header plus sky
    with open(obj_file, "w") as f:
        f.write("# IMAGE PARAMETERS\n")

        # restrict maximum number of degrees in polynomial
        maxdeg = nband
        if setup.do_restrict == 1:
            # for b in range(1, nband+1):
            for b in range(nband):
                image_data = fits.getdata(image_stamp_list[b] + ".fits")
                mask_data = fits.getdata(mask_file[b] + ".fits")
                primary_mask = fits.getdata(mask_primary_file + ".fits")

                n_primary_pixels = float(np.count_nonzero(primary_mask == 1))
                # find the "bad" pixels within the primary masked region(primary_mask==1)
                bad_pixels = (primary_mask == 1) & ((mask_data == 1) | (image_data == 0))
                n_bad_primary_pixels = float(np.count_nonzero(bad_pixels))
                # If more than restrict_frac_primary% are bad, lower maxdeg
                frac_bad = n_bad_primary_pixels / n_primary_pixels
                if frac_bad > (float(setup.restrict_frac_primary) / 100.0):
                    maxdeg -= 1

        # input image
        A_po = ""
        for b in range(nband):
            A_po = A_po + setup.outdir + image_stamp_list[b].strip() + ".fits"
            if b < (nband - 1):
                A_po = A_po + ","
        f.write(f"A) {A_po}   #input file\n")

        if setup.version >= 4.0:
            A1_po = ""
            for b in range(nband):
                # A1_po = A1_po + setup.stamp_pre[b].strip()
                A1_po = A1_po + label_list[b]
                if b < (nband - 1):
                    A1_po = A1_po + ","
            f.write(f"A1) {A1_po}     # Band labels (can be omitted if fitting a single band)\n")

            A2_po = ""
            for b in range(nband):
                # A2_po = A2_po + setup.wavelength[b].strip()
                A2_po = A2_po + wave_list[b]

                if b < (nband - 1):
                    A2_po = A2_po + ","
            f.write(
                f"A2) {A2_po}     # Band wavelengths (choice of wavelength units is arbitrary, as long as consistent)\n"
            )

        # output image
        f.write(f"B) {setup.outdir+out_file}.fits    # output file name\n")

        # noise image
        C_po = ""
        for b in range(nband):
            if sigma_file[b].strip() != "none":
                addtion = setup.outdir + sigma_file[b].strip()
            else:
                addtion = "none"
            C_po += addtion
            if b < (nband - 1):
                C_po += ","
        f.write(f"C) {C_po}           # Noise image name (made from data if blank or 'none')\n")

        # PSF image
        D_po = ""
        for b in range(nband):
            D_po = D_po + setup.outdir + psf_file[b].strip()
            if b < (nband - 1):
                D_po = D_po + ","
        f.write(f"D) {D_po} kernel  # Input PSF image and (optional) diffusion kernel\n")
        f.write(f"E) 1           # PSF oversampling factor relative to data\n")

        # mask image
        F_po = ""
        for b in range(nband):
            F_po = F_po + setup.outdir + mask_file[b].strip() + ".fits"
            if b < (nband - 1):
                F_po = F_po + ","
        f.write(f"F) {F_po}\n")

        f.write(f"G) {setup.outdir + constr_file}\n")
        f.write(f"H) 1 {xmax} 1 {ymax}       # Image region to fit (xmin xmax ymin ymax)\n")
        f.write(f"I) {int(round(conv_box))}   {int(round(conv_box))}         # Size of convolution box (x y)\n")

        J_po = ""
        for b in range(nband):
            zpt_str = str(zero_list[b])
            J_po += zpt_str
            if b < nband - 1:
                J_po += ","
        f.write(f"J) {J_po}     # Magnitude photometric zeropoint\n")

        f.write(f"K) {plate_scl:.5f} {plate_scl:.5f}           # Plate scale (dx dy).\n")
        f.write("O) regular             # Display type (regular, curses, both)\n")
        f.write("P) 0                   # Create output only? (1=yes; 0=optimize)\n")
        f.write("S) 0                   # Modify/create objects interactively?\n")
        f.write(f"W) {setup.gal_output} # GALFIT output file format\n")
        f.write("\n")
        f.write("\n")

        f.write("# sky\n")
        f.write("\n")
        f.write(" 0) sky\n")
        sky_po = ""
        sky_po2 = ""

        if use_cstsky is False:
            for b in range(nband):
                if os.path.exists(sky_file[b].strip()) is False:
                    raise FileNotFoundError(
                        f"sky file corresponding to current object was not found in band {setup.stamp_pre[b].strip()}"
                    )
                with open(sky_file[b].strip(), "r") as fsky:
                    parts = fsky.read().split()
                    sky, dsky, skyrad, sky_magobj, flag = [float(parts[i]) for i in range(5)]
                # Format the sky value
                if sky > 1.0:
                    used_sky = f"{sky:.3f}"
                else:
                    used_sky = f"{sky:.4g}"
                # Build the comma-separated strings
                sky_po += used_sky
                sky_po2 += "0"
                if b < (nband - 1):
                    sky_po += ","
                    sky_po2 += ","

        else:
            for b in range(nband):
                sky = cstsky_list[b]
                # Format the sky value
                if sky > 1.0:
                    used_sky = f"{sky:.3f}"
                else:
                    used_sky = f"{sky:.4g}"
                # Build the comma-separated strings
                sky_po += used_sky
                sky_po2 += "0"
                if b < (nband - 1):
                    sky_po += ","
                    sky_po2 += ","

        band_po = " "
        if (setup.version >= 4.0) and (nband > 1):
            band_po = "band"
        f.write(f" 1) {sky_po}    {sky_po2}  {band_po}       # sky background       [ADU counts]\n")

        skyg_po = ""
        skyg_po2 = ""
        for b in range(nband):
            skyg_po = skyg_po + "0.000"
            skyg_po2 = skyg_po2 + "0"
            if b < (nband - 1):
                skyg_po += ","
                skyg_po2 += ","
        f.write(f" 2) {skyg_po}    {skyg_po2}  {band_po}      # dsky/dx (sky gradient in x)\n")
        f.write(f" 3) {skyg_po}    {skyg_po2}  {band_po}      # dsky/dy (sky gradient in y)\n")
        f.write(" Z) 0                  # output image\n")
        f.write("\n")
        f.write("\n")

        # define all paths and names again
        # orgim = setup.images
        # orgwheights = setup.weights
        # outpath = setup.outpath
        # outpath_band = setup.outpath_band
        # outpre = setup.outpre

        # outpath_galfit = outpath[0] + setup.galfit_out_path # 1D array
        # outpath_pre = outpath_band + outpre
        # outpath_file = outpath
        # for q in range(nband+1):
        #    outpath_file[q] = outpath_pre[q] + setup.stamp_pre[q] + '.'
        # outpath_file_no_band = outpath
        # for q in range(nband+1):
        #    outpath_file_no_band[q]=outpath[q]+outpre[q]'''

        # find the GALFIT output file for the current contributing source
        num_current = str(table[current]["label"])
        # find the faintest source with proper magnitude measurement (non 99) and
        # correct 99 sources
        nn = np.where(table[objects]["mag_auto"] > 80)
        n_nn = nn[0].size
        if n_nn > 0:
            good_mag = np.where(table[objects]["mag_auto"] < 80)
            ngood_mag = good_mag[0].size
            if ngood_mag == 0:
                table[objects[nn]]["mag_auto"] = zero_list[0]
            else:
                table[objects[nn]]["mag_auto"] = max(table[objects[good_mag]["mag_auto"]]) + 2

        # loop over all (primary & secondary) sources
        for i in range(len(objects)):
            object_description = " "
            # secout_file = outpath_galfit[0] + outpre[0,0] + str(table[objects[i]]['label']) + setup.galfit_out + '.fits'
            secout_file = "./galfit/output" + str(table[objects[i]]["label"]) + ".fits"
            # object_id = outpre[0,0] + str(table[objects[i]]['label'])
            object_id = str(table[objects[i]]["label"])

            if os.path.exists(secout_file):
                # sources with existing fit will be included as static source
                par = read_sersic_results(secout_file, nband, setup)

                # problem: position from GALFIT is relative to original postage stamp
                # need to compute offset using SExtractor input for that fit
                # tb = ascii.read(outpath_file[idx,0]+out_cat) ##???? do not understand
                # itb = np.where(tb['label'] == table[objects[i]]['label'])[0][0]

                stamp_file = stamp_file
                cols = ["id", "x", "y", "ra", "dec", "xlo", "xhi", "ylo", "yhi", "pixscal"]
                cat = ascii.read(stamp_file, names=cols)
                icat = np.where(cat["id"] == table[objects[i]]["label"])[0][0]

                par.x_galfit = par.x_galfit + cat["xlo"][icat]  # need to be updated
                par.x_galfit_band = par.x_galfit_band + cat["xlo"][icat]

                par.y_galfit = par.y_galfit + cat["ylo"][icat]
                par.y_galfit_band = par.y_galfit_band + cat["ylo"][icat]

                object_description = "(primary/secondary) object has already been fit, galfit output file exists. Reading result from file"

                fix = ["0", "0", "0", "0", "0", "0", "0"]

            else:
                # sources without fit will be included as free fit, i.e., fainter secondaries

                # still reading in files, because it returns the correct FORMAT, but
                # with useless values in it. As they will be replaced here, that does
                # not matter
                par = read_sersic_results(secout_file, nband, setup)

                par.x_galfit = table[objects[i]]["xcentroid"] + 1
                par.x_galfit_band = [par.x_galfit] * nband

                par.y_galfit = table[objects[i]]["ycentroid"] + 1
                par.y_galfit_band = [par.y_galfit] * nband

                par.mag_galfit = table[objects[i]]["mag_auto"]
                par.mag_galfit_band = [par.mag_galfit] * nband  # have not add offset yet

                par.re_galfit = 10.0 ** (-0.79) * table[objects[i]]["flux_radius"] ** 1.87
                par.re_galfit_band = [par.re_galfit] * nband

                par.n_galfit = 2.5
                par.n_galfit_band = [par.n_galfit] * nband

                par.q_galfit = 1 - table[objects[i]]["ellipticity"]
                par.q_galfit_band = [par.q_galfit] * nband

                par.pa_galfit = table[objects[i]]["orientation"] - 90.0
                par.pa_galfit_band = [par.pa_galfit] * nband

                object_description = "(primary/secondary) object has not yet been fit, output file does not exist"
                fix = ["1", "1", "1", "1", "1", "1", "1"]

                # if the source position is off the frame (postage stamp?): fix the position, PA and q
                # this is only for fainter secondaries that has not yet been fit.
                if (
                    ((table[objects[i]]["xcentroid"] + 1 - corner[0]) < 1)
                    or ((table[objects[i]]["xcentroid"] + 1 - corner[0]) > xmax)
                    or ((table[objects[i]]["ycentroid"] + 1 - corner[1]) < 1)
                    or ((table[objects[i]]["ycentroid"] + 1 - corner[1]) > ymax)
                ):

                    object_description = (
                        "(primary/secondary) object has not yet been fit, output file does not exist, outside of frame"
                    )
                    fix[0] = "0"
                    fix[1] = "0"
                    fix[5] = "0"
                    fix[6] = "0"

            # check check some constraints and set starting values accordingly if neccessary
            # This is to ensure input values are reasonable.
            if np.isfinite(par.re_galfit) is False:
                par.re_galfit = max(table[objects[i]]["flux_radius"], 3)  # ensure larger than 3 pixels
                par.re_galfit_band = [par.re_galfit] * nband

            if par.re_galfit < 0:
                par.re_galfit = max(table[objects[i]]["flux_radius"], 3)  # ensure larger than 3 pixels
                par.re_galfit_band = [par.re_galfit] * nband

            par.re_galfit = max(min(par.re_galfit, float(conmaxre)), 0.3)
            par.re_galfit_band = [max(min(val, float(conmaxre)), 0.3) for val in par.re_galfit_band]
            par.n_galfit = max(min(par.n_galfit, setup.conmaxn), setup.conminn)
            par.n_galfit_band = [max(min(val, setup.conmaxn), setup.conminn) for val in par.n_galfit_band]
            par.q_galfit = min(max(par.q_galfit, 0.01), 1)
            par.q_galfit_band = [min(max(val, 0.01), 1) for val in par.q_galfit_band]
            par.pa_galfit = min(max(par.pa_galfit, -360), 360)
            par.pa_galfit_band = [min(max(val, -360), 360) for val in par.pa_galfit_band]

            # filew = open(obj_file, 'a') # append mode
            # Write a blank line
            f.write("\n")
            f.write("# Sersic function\n")
            f.write(f"# {object_description}\n")
            f.write(f"# {object_id}\n")
            f.write(" 0) sersic             # Object type\n")

            x_po = ""
            x_po_fit = ""
            y_po = ""
            y_po_fit = ""

            for b in range(nband):
                x_po = x_po + str(round(par.x_galfit_band[b] - corner[0], 2))
                y_po = y_po + str(round(par.y_galfit_band[b] - corner[1], 2))
                if b < nband - 1:
                    x_po = x_po + ","
                    y_po = y_po + ","

            if fix[0] == "1":
                x_po_fit = str(min(int(setup.cheb[0]) + 1, maxdeg))
            else:
                x_po_fit = "0"

            if fix[1] == "1":
                y_po_fit = str(min(int(setup.cheb[1]) + 1, maxdeg))
            else:
                y_po_fit = "0"

            if setup.version >= 4.0:
                f.write(" 1) " + x_po + "  " + x_po_fit + "  " + band_po + "   # position x     [pixel]\n")
                f.write(" 2) " + y_po + "  " + y_po_fit + "  " + band_po + "   # position y     [pixel]\n")
            else:
                f.write(
                    " 1) "
                    + x_po
                    + "  "
                    + y_po
                    + "   "
                    + x_po_fit
                    + " "
                    + y_po_fit
                    + "   # position x, y        [pixel]\n"
                )

            mag_po = ""
            mag_po_fit = ""
            for b in range(nband):
                mag_po = mag_po + str(round(par.mag_galfit_band[b], 2))
                if b < nband - 1:
                    mag_po = mag_po + ","

            if fix[2] == "1":
                mag_po_fit = str(min(int(setup.cheb[2]) + 1, maxdeg))
            else:
                mag_po_fit = "0"

            f.write(" 3) " + mag_po + "    " + mag_po_fit + "   " + band_po + "    # total magnitude\n")

            re_po = ""
            re_po_fit = ""
            for b in range(nband):
                re_po = re_po + str(round(par.re_galfit_band[b], 2))
                if b < nband - 1:
                    re_po = re_po + ","
            if fix[3] == "1":
                re_po_fit = str(min(int(setup.cheb[3]) + 1, maxdeg))
            else:
                re_po_fit = "0"
            f.write(" 4) " + re_po + "    " + re_po_fit + "   " + band_po + "       #     R_e              [Pixels]\n")

            n_po = ""
            n_po_fit = ""
            for b in range(nband):
                n_po = n_po + str(round(par.n_galfit_band[b], 2))
                if b < nband - 1:
                    n_po = n_po + ","
            if fix[4] == "1":
                n_po_fit = str(min(int(setup.cheb[4]) + 1, maxdeg))
            else:
                n_po_fit = "0"
            f.write(
                " 5) " + n_po + "    " + n_po_fit + "   " + band_po + "       # Sersic exponent (deVauc=4, expdisk=1)\n"
            )

            q_po = ""
            q_po_fit = ""
            for b in range(nband):
                q_po = q_po + str(round(par.q_galfit_band[b], 4))
                if b < nband - 1:
                    q_po = q_po + ","
            if fix[5] == "1":
                q_po_fit = str(min(int(setup.cheb[5]) + 1, maxdeg))
            else:
                q_po_fit = "0"
            if setup.version == 0:
                strvar = " 8) "
            else:
                strvar = " 9) "
            f.write(strvar + q_po + "    " + q_po_fit + "   " + band_po + "       # axis ratio (b/a)\n")

            pa_po = ""
            pa_po_fit = ""
            for b in range(nband):
                pa_po = pa_po + str(round(par.pa_galfit_band[b], 2))
                if b < nband - 1:
                    pa_po = pa_po + ","
            if fix[6] == "1":
                pa_po_fit = str(min(int(setup.cheb[6]) + 1, maxdeg))
            else:
                pa_po_fit = "0"
            if setup.version == 0:
                strvar = "9) "
            else:
                strvar = "10) "
            f.write(
                strvar
                + pa_po
                + "    "
                + pa_po_fit
                + "   "
                + band_po
                + "       # position angle (PA) [Degrees: Up=0, Left=90]\n"
            )

            f.write(" Z) 0                  # output image (see above)\n")
            f.write("\n")
        f.close()
